var INITIAL_WORLD_WIDTH = 128; // INIT
var INITIAL_WORLD_HEIGHT = 82; // INIT

var INITIAL_SIMULATION_SETTINGS = {
    LIFETIME_MAX: 300,
    LIFETIME_MAX_C: 300,
    LIFETIME_MIN: 100,
    SEED_POWER: 500,
    SEED_MAX: 1000,
    CHILDHOOD: 25,
    FOOD_ENERGY: 15,
    ENERGYCOST_SEED: 5,
    ENERGYCOST_OBSTACLE: 1,
    ENERGYCOST_OBSTACLE_C: 1,
    ENERGYCOST_FORK: 15,
    OBSTACLETIME: 1500, //400
    FOSSILTIME: 300, //400
    EPROBOTS_MAX: 150,
    TRACETIME: 32,
    KINDERGARTEN: false,
    BORDERJUMP: true,
    SENSE: true,
    PROGRAM_LENGTH: 100,
    MUTATE_POSSIBILITY: 0.01,
    MUTATE_STRENGTH: 400
};

var GLOBAL_SETTINGS = {
    SLEEPTIME: 0, // GLOBAL
    LOG_STATS: false // GLOBAL
}
