var INITIAL_SIMULATION_SETTINGS = {
    OBJECT_COUNT: 5000,
    LIFETIME: 100,
    TRACETIME: 32,
    FOSSILTIME: 100, //400
    SLEEPTIME: 0,
    KINDERGARTEN: false,
    ENERGY_WIDTH: "MAX"
};

var INITIAL_WORLD_WIDTH = 128;
var INITIAL_WORLD_HEIGHT = 100;

var GLOBAL_SETTINGS = {
    PROGRAM_LENGTH: 100,
    BORDERJUMP: true,
    SENSE: true,
    LOG_STATS: false
}
