var INITIAL_WORLD_WIDTH = 156; // INIT
var INITIAL_WORLD_HEIGHT = 100; // INIT

var INITIAL_SIMULATION_SETTINGS = {

    FOSSILTIME: 300, //400
    EPROBOTS_MAX: 200,

    LIFETIME_MAX: 300,
    START_ENERGY: 50,
    FOOD_ENERGY: 150,
    ENERGYCOST_FORK: 120,

    LIFETIME_MAX_C: 300,
    START_ENERGY_C: 50,
    FOOD_ENERGY_C: 150,
    ENERGYCOST_FORK_C: 60,

    SEED_POWER: 500,
    SEED_MAX: 1000,
    TOXIN_POWER: 500,
    TOXIN_MAX: 1000,
    ENERGYCOST_SEED: 5,
    ENERGYCOST_TOXIN: 5,
    ENERGYCOST_OBSTACLE: 5,
    OBSTACLETIME: 1500, //400

    TRACETIME: 32,
    KINDERGARTEN: true,
    BORDERJUMP: true,
    SENSE: true,
    PROGRAM_LENGTH: 100,
    PROGRAM_STEPS: 100,
    MUTATE_POSSIBILITY: 0.01,
    MUTATE_STRENGTH: 400
};

var GLOBAL_SETTINGS = {
    SLEEPTIME: 0, // GLOBAL
    LOG_STATS: false // GLOBAL
}
